image:
  repository: OlenaSiller/users-api
  tag: 1.2.3
  pullPolicy: IfNotPresent

serviceAccount:
  create: true

service:
  type: ClusterIP
  name: users-api
  port: 8000

ingress:
  enabled: false

autoscaling:
  enabled: true  
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
